# Generated by Django 5.1.3 on 2025-02-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Functionality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pythonCode', models.CharField(max_length=10000)),
                ('_type', models.BooleanField(default=True)),
                ('function', models.ManyToManyField(to='Functionality.functionality')),
            ],
        ),
    ]
