# Generated by Django 5.1.3 on 2024-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Functionality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pythonCode', models.CharField(max_length=10000)),
                ('_type', models.BooleanField(default=True)),
                ('function', models.ManyToManyField(to='Functionality.functionality')),
            ],
        ),
    ]
