# Generated by Django 5.1.3 on 2025-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='belongs',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
