# Generated by Django 5.1.3 on 2024-11-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agents', models.CharField(max_length=10000)),
                ('input', models.CharField(max_length=10000)),
            ],
        ),
    ]
