# Generated by Django 5.1.3 on 2025-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionality',
            name='belongs',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
